name = "gleamering_star"
version = "0.1.0"

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"
gleam_http = "~> 3.5"
gleam_erlang = "~> 0.25"
gleam_crypto = "~> 1.3"
mist = "~> 1.2"
sqlight = "~> 0.8"
wisp = "~> 0.5"
gleamering_hope = { path = "../gleamering_hope" }
glexec = ">= 1.0.3 and < 2.0.0"
dot_env = ">= 1.0.0 and < 2.0.0"
gleam_json = "~> 1.0.1"

[dev-dependencies]
gleeunit = "~> 1.0"
