#put your docker-compose contents here and link the docker's port with your chosen external port!
version: "3"
services:
    counter_block_chaining:
        container_name: counter_block_chaining
        build: .
        logging:
            driver: "json-file"
        ports:
            - "3000:2001"
